# example netlify.toml
[build]
  functions = "netlify/functions"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

[dev]
  command = "npm run start" # Command to start your dev server
  targetPort = 3000
  publish = "" # avoid static site deployment 

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
